### ISSUE TITLE
F5 to run it, get Uncaught Error Error: Could not find module root given file: "node:internal/modules/cjs/loader". Do you have a `package.json` file? 

### ISSUE THREAD

**Issue by inoutw** [continuedev/continue#1031]
### Before submitting your bug report

- [ ] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [ ] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Windows X86
- Continue: v0.8.27
- IDE: VSCode 1.78.2
```

### Description

I've installed all dependencies, and run the project, got this error:
Process exited with code 1
Uncaught Error Error: Could not find module root given file: "node:internal/modules/cjs/loader". Do you have a `package.json` file? 
    at getRoot (d:\workspace\github\continue\pkg\out\index.js:13151:17)
    at bindings (d:\workspace\github\continue\pkg\out\index.js:13078:37)
    at ../core/node_modules/sqlite3/lib/sqlite3-binding.js (d:\workspace\github\continue\pkg\out\index.js:13166:41)
    at __require (d:\workspace\github\continue\pkg\out\index.js:18:51)
    at ../core/node_modules/sqlite3/lib/sqlite3.js (d:\workspace\github\continue\pkg\out\index.js:13216:20)
    at __require (d:\workspace\github\continue\pkg\out\index.js:18:51)
    at <anonymous> (d:\workspace\github\continue\pkg\out\index.js:283604:30)
    at Module._compile (internal/modules/cjs/loader:1368:14)
    at Module._extensions..js (internal/modules/cjs/loader:1426:10)
    at Module.load (internal/modules/cjs/loader:1205:32)
    at Module._load (internal/modules/cjs/loader:1021:12)
    at executeUserEntryPoint (internal/modules/run_main:142:12)
    at <anonymous> (internal/main/run_main_module:28:49)

**Comment by sestinj** [comment]
Hi @inoutw, thanks for sharing the logs! I finally found the cause of this and it appears to have been solved by renaming the pkg folder to "binary" to avoid a naming conflict. I'm going to close the issue, but please re-open and let me know if pulling the latest still leads to the same exact error.

**Comment by micli** [comment]
@sestinj Sorry, I think it should be reopen. Because I checked out v0.8.25 version which was fixed by PR https://github.com/continuedev/continue/commit/3ad9e3e5f22bd4f1823ab8a8fc9ec745ebb62ac0 .
However, it still does not work as below:
<img width="1080" alt="截屏2024-05-09 上午9 12 23" src="https://github.com/continuedev/continue/assets/2059006/bbc6d970-2bad-4aad-9313-350ece5a0eb3">

**Comment by sestinj** [comment]
@micli Is this happening on the preview branch as well?

**Comment by AnnoyingTechnology** [comment]
Any chance that this is related ?

`Error: Could not find module root given file: "/snapshot/continue-dist/binary/out/index.js". Do you have a `package.json` file?`

This happens once I `./gradlew buildPlugin` and install it on PhpStorm. 

I ran the extension in development mode before building the plugin, and it did work. Maybe a packaging issue ?

**Comment by AnnoyingTechnology** [comment]
Dirty workaround : 
* unzip an official build
* unzip your build
* copy the package.json from the official build (alongside index.node and continue-binary)
* rezip yours: works.
