### ISSUE TITLE
Context Provider API broke down

### ISSUE THREAD

**Issue by samir-abis-everest** [continuedev/continue#2010]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: linux-arm64
- Continue: main/dev/preview
- IDE: vscode - code-server
```

### Description

Seems in the recent versions of Continue preview, the context providers are not working anymore.

I implemented context providers through the API connection and they show in the list, but when I try to run them unfortunately they show no results.

@fry69 mentioned that there were recent changes to ESM for `config.ts`, might be a cause?
Discussion here: https://discord.com/channels/1108621136150929458/1273194528513458248

This wasn't the case a few builds ago. 

![image](https://github.com/user-attachments/assets/bc9e025f-d5f7-465e-a0d1-1751a63a8a42)

here's an older build that runs the command with results
![image](https://github.com/user-attachments/assets/e2599af2-6966-44fc-b93a-ab7905bcd0cf)

and here's a newer build:
![image](https://github.com/user-attachments/assets/8fedc0d4-6992-4c7d-83d7-6d987a23c30a)

### To reproduce

1. Develop a Context Provider with submenu through extension handling
2. Verify if the submenu loads correctly

**Comment by Patrick-Erichsen** [comment]
Hi @samir-abis-everest , thanks for opening this. To clarify, you have a context provider with submenu items, but when you select the context provider, the submenu is empty?

Could you clarify what you mean by this?

> might be? I'm not sure if it's related because I build the configurations in my extensions instead of Continue

There was a bug with config.ts related to us moving to a newer Typescript target but that was resolved and I don't believe would have an impact here.

**Comment by samir-abis-everest** [comment]
Hi @Patrick-Erichsen.

> you have a context provider with submenu items, but when you select the context provider, the submenu is empty?

Correct

> Could you clarify what you mean by this?

I just tried out with a context provider directly in the `config.ts` (the example one of the documentation, reading `.md` files) and it works on the older build, while on the new build it still doesn't work.

**Comment by Patrick-Erichsen** [comment]
Got it - mind sharing your config.ts as well?

**Comment by samir-abis-everest** [comment]
I've digged more through this in the debugger and this is the current status:

new version:
```log
[2024-08-28T11:06:38] [DEBUG] Executing getSubmenuContextItems. Provider: lotse-context Query:  Limit: 70
[2024-08-28T11:06:38] [DEBUG] Executing getSubmenuSearchResults. Provider: lotse-context Query: 
[2024-08-28T11:06:38] [DEBUG] Current minisearches: []
[2024-08-28T11:06:38] [DEBUG] No minisearch found for provider: lotse-context
[2024-08-28T11:06:38] [DEBUG] Using fallback results: 0
```

old version:
```log
[2024-08-28T11:08:46] [DEBUG] Logging initialized
[2024-08-28T11:09:12] [DEBUG] Executing getSubmenuContextItems. Provider: lotse-context Query:   Limit: 70
[2024-08-28T11:09:12] [DEBUG] Executing getSubmenuSearchResults. Provider: lotse-context Query:  
[2024-08-28T11:09:12] [DEBUG] Current minisearches: ["everest-nodes","everest-docs","lotse-context","markdown"]
[2024-08-28T11:09:12] [DEBUG] Search results for lotse-context: 0
[2024-08-28T11:09:12] [DEBUG] Using fallback results: 8
```

**Comment by samir-abis-everest** [comment]
https://github.com/continuedev/continue/pull/2124
