### ISSUE TITLE
Cannot sign in with VSCodium due to invalid redirect.

### ISSUE THREAD

**Issue by Patrick-Erichsen** [continuedev/continue#4406]
### Before submitting your bug report

- [ ] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [ ] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [ ] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
OS: macOS
Continue version: 1.0.1
IDE version: VSCodium 1.94.4
```

### Description

When I click "sign in", I get to open the following url that includes redirect_uri=vscodium://Continue.continue, which leads to an error page.

![Image](https://github.com/user-attachments/assets/9ae8ac04-c92b-4bb0-a700-f49a822343bf)

### Log output

```Shell

```

**Comment by SunsetMkt** [comment]
I'm experiencing a similar problem. I guess there's something wrong with continue.dev account or auth system.

**Comment by sestinj** [comment]
Thanks for the report. This is happening because we have to explicitly name the IDE and allow each redirect URL—we'd done it for code-oss but somehow missed vscodium! It should now be fixed for onboarding and a release will go out tomorrow to fix authentication

**Comment by joewhicks** [comment]
I am having the same problem. Not sure if the fix has been pushed yet.

**Comment by Patrick-Erichsen** [comment]
Release has not gone out quite yet but will be by end of day @joewhicks

**Comment by alkat19** [comment]
Is there any progress on that?

**Comment by joewhicks** [comment]
@alkat19 I can now l sign in via the "get started" button in the positron extension. However positron is not receiving confirmation of the sign in, so it hangs as "signing in to continue"

**Comment by alkat19** [comment]
I tried continue 1.1.3 and 1.1.5, I am still unable to sign in. My current positron version: 
Positron Version: 2025.03.0 (Universal) build 116
Code - OSS Version: 1.96.0
Commit: 7f0f93873e8b24c9f393bb3586724f4783c5e72c
Date: 2025-03-01T18:51:44.014Z (6 days ago)
Electron: 32.2.6
Chromium: 128.0.6613.186
Node.js: 20.18.1
V8: 12.8.374.38-electron.0
OS: Darwin arm64 24.3.0

**Comment by alkat19** [comment]
Is there any updates on that ?

**Comment by lynxrv21** [comment]
I'm having the same issue with VSCodium and Continue 1.1.11

Version: 1.98.2
Release: 25072
Commit: c6b0b68cdb1a0ec15f1eb97d903aa1855445fd42
Date: 2025-03-13T18:16:56.492Z
Electron: 34.2.0
ElectronBuildId: undefined
Chromium: 132.0.6834.196
Node.js: 20.18.2
V8: 13.2.152.36-electron.0
OS: Darwin arm64 24.3.0

**Comment by noahziheng** [comment]
I also encountered the same issue, any progress?

**Comment by tomasz-stefaniak** [comment]
Potentially related: https://github.com/continuedev/continue/issues/4592

(I'm trying to bring all sing-in issues together)

**Comment by nikaro** [comment]
What is the status of this issue? There are comments saying it should be resolved in some release. But i'm on the latest available and and still cannot login :-(

I'm using VSCodium on macOS, and use Firefox.

**Comment by DocMAX** [comment]
![Image](https://github.com/user-attachments/assets/d901a447-80d7-4e32-a9d0-9343cf2827ed)
when i try to sign in from code oss.

**Comment by joeytwiddle** [comment]
I am getting this while using code 1.99.3-1 (Code OSS) on Manjaro . Using `⚙ > Sign In` resulted in the error. Using the `Get started` button worked, but it wasn't visible at first!

Workaround:

1. Stop Code
2. Make a backup: `cp -ai ~/.config/Code ~/.config/Code.BACKUP1`
3. `cd ~/.config/Code`
4. Remove the Local Storage folder (e.g. `trash "Local Storage/"` or `rm -rf "Local Storage"`)
   Please note that this may lose data related to other extensions.
6. Start Code
7. Focus the Continue Chat sidebar
8. **DO NOT** use `⚙ > Sign In` (because that results in the error above)
9. **DO** use the `Get started` button to sign in (which works)

Bugs to fix:

1. Continue just seems to quietly stop working when I am signed out, leaving me clueless. Ideally it should tell me _why_ it isn't working, and how to fix it.
   E.g. a popup or error message: "Continue autocomplete is enabled, but it will not work while you are signed out. Please ____ to sign in again."
3. Ensure that sign in with `⚙ > Sign In` works the same as sign in with `Get started` button.
4. Don't sign me out in the first place! (No idea why that happened.)

I got the fix using pre-release version 1.1.34 but I had previously been on the release version (according to the store page, it's the same version).

Thank you for this extension!

**Comment by joshuacox** [comment]
As an aside note, I had to uninstall code otherwise the redirect went to code everytime even though I was initiating the authorization from VScodium.  After uninstalling code I could perform the auth.
