### ISSUE TITLE
Indexing settings get ignored

### ISSUE THREAD

**Issue by Katzenwerfer** [continuedev/continue#4456]
### Before submitting your bug report

- [x] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [x] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [x] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Windows 11 24H2 (26100.3194)
- Continue version: v1.0.2
- IDE version: VS Code 1.97.2
```

### Description

Indexing settings get ignored on both shared and workspace files. This causes files in folders/workspaces to always get indexed, regardless of user configuration.
For the record, this issue started in v0.8.68, though with slight differences. Rolling back to v0.8.66 works fine.

### To reproduce

1. Disable indexing in the sidebar's settings
2. Open a folder or a multi-folder workspace
3. Check the "index.sqlite" changing (it shouldn't)

Or

1. In a folder, create a ".continuerc.json" that has the next config
```json
{"disableIndexing": true}
```
2. Open the folder
3. Check the "index.sqlite" changing (it shouldn't)

Worth noting that it's ideal to clear the index file to notice its growth.

**Comment by Katzenwerfer** [comment]
I would attach a log, but I didn't find anything related to the indexing behavior.
I could try pulling one if requested, though the issue is consistently reproducible.

**Comment by RomneyDa** [comment]
Fixed by https://github.com/continuedev/continue/pull/4531

**Comment by Katzenwerfer** [comment]
Hi. I tried the latest pre-release, and it seems to partially work.

1. New files don't get indexed in an open workspace, but reloading the window makes it, so all files get indexed regardless of settings.
2. The `disableIndexing` setting in ".continuerc.json" still gets ignored and follows the global setting.
   - The first listed issue might be affecting this.
3. There are instances of the extension indexing files if a ".continueignore" is modified while indexing is globally disable.
   - The first listed issue might be affecting this.

Should I open a new issue on these?
