### ISSUE TITLE
Keyboard shortcuts on Windows show Mac shortcuts

### ISSUE THREAD

**Issue by TyDunn** [continuedev/continue#791]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Windows
- Continue: Latest
- IDE: VS Code
```

### Description

> Oh, and you're assuming my computer's make lol.

> Some of us use Windows machines. So shortcuts showing Mac keys is not very inclusive.

From user on r/LocalLlama [here](https://www.reddit.com/r/LocalLLaMA/comments/1aexjjt/comment/kkbpov4/?utm_source=share&utm_medium=web2x&context=3)

**Comment by EmmaWebGH** [comment]
I just had the exact same problem, installed and tried to do the tutorial that auto-opens, and the shortcut keys are all wrong. I had to come to the docs to find out what the equivalent windows keys were.

**Comment by rootedbox** [comment]
Fixed in https://github.com/rootedbox/continue/commit/1f0ecdf49877fd3b577e5e8b02b4ad0e94a4ab7f

**Comment by Dorish** [comment]
> I just had the exact same problem, installed and tried to do the tutorial that auto-opens, and the shortcut keys are all wrong. I had to come to the docs to find out what the equivalent windows keys were.

Could you share the docs you refered to for the shortcut keys? Thanks in advance!

**Comment by EmmaWebGH** [comment]
@Dorish pretty sure it was the extension page in VScode! 
Anyway since then many people have bagged that I use windows, alas I am not a "real" dev on linux or Mac,. I only do this as a hobby and for entertainment / enjoyment / occasional self torture.

**Comment by sestinj** [comment]
@Dorish @ewebgh33 I just went through the tutorial to make things a bit clearer and double-checked that we use the correct version for each OS: https://github.com/continuedev/continue/commit/d4d1a8eec9fa253e34d650316a73172bcdec3cac

Going to close the issue, but I know that we've slipped up before and forgotten to parametrize in some of the many many places where we show our shortcuts. Goal is to get it right everywhere, so if you find a mistake please re-open and let me know!

**Comment by nebula-it** [comment]
Hey @sestinj
Just reopening this, since the code suggestions in the editor still show mac shortcuts on Windows. See 
![image](https://github.com/continuedev/continue/assets/40148908/6109170d-d34c-4b3f-ab2b-5e0f35fee1c7)
I'm on the latest stable `v0.8.25`

**Comment by sestinj** [comment]
@nebula-it Just changed: https://github.com/continuedev/continue/commit/6b9de715a3f683b4cc0771b3ccdbe107a5eb90b2

Was using the symbol for Alt, but this is probably too esoteric
